---
- name: Update package cache > 3600 seconds old
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages to their latest version
  ansible.builtin.package:
    upgrade: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file
  changed_when: reboot_required_file.stat.exists
  notify:
    - reboot server